# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: product-catalog-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: product-catalog.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend
#             port:
#               number: 80
#       - path: /api/products
#         pathType: Prefix
#         backend:
#           service:
#             name: product-service
#             port:
#               number: 5000
#       - path: /api/ratings
#         pathType: Prefix
#         backend:
#           service:
#             name: ratings-service
#             port:
#               number: 5001

